export const USER_ROLES = {
  ADMIN: "Admin",
  CUSTOMER: "Customer",
  SALES_REP: "Sales Rep",
  GENERAL_CONTRACTOR: "General Contractor",
  WORKER: "Worker",
};

export const PAGE_LIMIT = 20;

export const PROJECT_STATUSES = {
  CREATED: "Created",
  READY_TO_BE_ASSIGNED_TO_GC: "Ready to be assigned to GC",
  ASSIGNED_TO_GC: "Assigned to GC",
  GC_ACCEPTED: "GC Accepted",
  ON_SITE_INSPECTION_SCHEDULED: "On-site Inspection Scheduled",
  ON_SITE_INSPECTION_IN_PROGRESS: "On-site Inspection In-progress",
  UPDATING_PROPOSAL: "Updating Proposal",
  REVIEWING_PROPOSAL: "Reviewing Proposal",
  READY_FOR_INSTALLATION: "Ready for Installation",
  INSTALLATION_STARTED: "Installation Started",
  VALIDATING_PERMITS: "Validating Permits",
  CLOSING_OUT: "Closing Out",
  COMPLETED: "Completed",
};

export const PROJECT_STATUS_KEYS = {
  CREATED: "CREATED",
  READY_TO_BE_ASSIGNED_TO_GC: "READY_TO_BE_ASSIGNED_TO_GC",
  ASSIGNED_TO_GC: "ASSIGNED_TO_GC",
  GC_ACCEPTED: "GC_ACCEPTED",
  ON_SITE_INSPECTION_SCHEDULED: "ON_SITE_INSPECTION_SCHEDULED",
  ON_SITE_INSPECTION_IN_PROGRESS: "ON_SITE_INSPECTION_IN_PROGRESS",
  UPDATING_PROPOSAL: "UPDATING_PROPOSAL",
  REVIEWING_PROPOSAL: "REVIEWING_PROPOSAL",
  REJECTED: "REJECTED",
  READY_FOR_INSTALLATION: "READY_FOR_INSTALLATION",
  INSTALLATION_STARTED: "INSTALLATION_STARTED",
  VALIDATING_PERMITS: "VALIDATING_PERMITS",
  CLOSING_OUT: "CLOSING_OUT",
  COMPLETED: "COMPLETED",
};

export const PROJECT_STATUS_TRANSITIONS_SHOULD_COME_FROM = {
  [PROJECT_STATUS_KEYS.READY_TO_BE_ASSIGNED_TO_GC]: [
    PROJECT_STATUSES.CREATED,
    PROJECT_STATUSES.ASSIGNED_TO_GC, // When GC rejects the project
  ],
  [PROJECT_STATUS_KEYS.ASSIGNED_TO_GC]: [
    PROJECT_STATUSES.READY_TO_BE_ASSIGNED_TO_GC,
  ],
  [PROJECT_STATUS_KEYS.GC_ACCEPTED]: [PROJECT_STATUSES.ASSIGNED_TO_GC],
  [PROJECT_STATUS_KEYS.ON_SITE_INSPECTION_SCHEDULED]: [
    PROJECT_STATUSES.GC_ACCEPTED,
  ],
  [PROJECT_STATUS_KEYS.ON_SITE_INSPECTION_IN_PROGRESS]: [
    PROJECT_STATUSES.ON_SITE_INSPECTION_SCHEDULED,
  ],
  [PROJECT_STATUS_KEYS.UPDATING_PROPOSAL]: [
    PROJECT_STATUSES.ON_SITE_INSPECTION_IN_PROGRESS,
    PROJECT_STATUSES.REVIEWING_PROPOSAL, // When customer rejects the proposal and sales rep moves it back to updating proposal
  ],
  [PROJECT_STATUS_KEYS.REVIEWING_PROPOSAL]: [
    PROJECT_STATUSES.UPDATING_PROPOSAL,
  ],
  [PROJECT_STATUS_KEYS.READY_FOR_INSTALLATION]: [
    PROJECT_STATUSES.REVIEWING_PROPOSAL, // When sales rep updates the proposal and customer accepts
    PROJECT_STATUS_KEYS.UPDATING_PROPOSAL, // After sales rep says we need proposal update and later comes back saying its not necessary
    PROJECT_STATUSES.ON_SITE_INSPECTION_IN_PROGRESS, // When sales rep and GC thinks original proposal is good enough
  ],
  [PROJECT_STATUS_KEYS.INSTALLATION_STARTED]: [
    PROJECT_STATUSES.READY_FOR_INSTALLATION,
  ],
  [PROJECT_STATUS_KEYS.VALIDATING_PERMITS]: [
    PROJECT_STATUSES.INSTALLATION_STARTED,
  ],
  [PROJECT_STATUS_KEYS.CLOSING_OUT]: [PROJECT_STATUSES.VALIDATING_PERMITS],
  [PROJECT_STATUS_KEYS.COMPLETED]: [PROJECT_STATUSES.CLOSING_OUT],
};

export const TASK_STATUSES = {
  TO_DO: "To Do",
  IN_PROGRESS: "In Progress",
  COMPLETED: "Completed",
};

export const PROJECT_UPLOAD_TYPES = {
  contract: "contract",
  permit: "permit",
  inspection: "inspection",
  invoice: "invoice",
  other: "other",
};

export const AUTHORIZED_ROLES_FOR_MARKING_PROJECT_STATUS = {
  [PROJECT_STATUS_KEYS.READY_TO_BE_ASSIGNED_TO_GC]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
  ],
  [PROJECT_STATUS_KEYS.ASSIGNED_TO_GC]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
  ],
  [PROJECT_STATUS_KEYS.GC_ACCEPTED]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
    USER_ROLES.GENERAL_CONTRACTOR,
  ],
  [PROJECT_STATUS_KEYS.ON_SITE_INSPECTION_SCHEDULED]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
    USER_ROLES.GENERAL_CONTRACTOR,
  ],
  [PROJECT_STATUS_KEYS.ON_SITE_INSPECTION_IN_PROGRESS]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
    USER_ROLES.GENERAL_CONTRACTOR,
  ],
  [PROJECT_STATUS_KEYS.UPDATING_PROPOSAL]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
  ],
  [PROJECT_STATUS_KEYS.REVIEWING_PROPOSAL]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
  ],
  [PROJECT_STATUS_KEYS.READY_FOR_INSTALLATION]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
    USER_ROLES.GENERAL_CONTRACTOR,
  ],
  [PROJECT_STATUS_KEYS.INSTALLATION_STARTED]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
    USER_ROLES.GENERAL_CONTRACTOR,
  ],
  [PROJECT_STATUS_KEYS.VALIDATING_PERMITS]: [
    USER_ROLES.ADMIN,
    USER_ROLES.SALES_REP,
  ],
  [PROJECT_STATUS_KEYS.CLOSING_OUT]: [USER_ROLES.ADMIN, USER_ROLES.SALES_REP],
  [PROJECT_STATUS_KEYS.COMPLETED]: [USER_ROLES.ADMIN, USER_ROLES.SALES_REP],
};
